version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=dev-secret-change-me
      - ALLOWED_HOSTS=*
      - DATABASE_URL=sqlite:///db.sqlite3
    volumes:
      - .:/app
